src/Daiquiri/ReservationBundle/Entity/Request.php
<?php

namespace Daiquiri\ReservationBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * Request
 * 
 * @ORM\Table() 
 * @ORM\Entity()
 * @ORM\InheritanceType("JOINED")
 * @ORM\DiscriminatorColumn(name="type",type="string")
 * @ORM\DiscriminatorMap({"Request"="Request","RentalHouseRequest"="RentalHouseRequest","PackageRequest"="PackageRequest","CircuitRequest"="CircuitRequest","MedicalRequest"="MedicalRequest","TransferExclusiveRequest"="TransferExclusiveRequest","TransferColectiveRequest"="TransferColectiveRequest","CarRequest"="CarRequest","ExcursionRequest"="ExcursionRequest"})
 */
class Request {

    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="createAt", type="date")
     */
    private $createAt;

    /**
     * @var string
     *
     * @ORM\Column(name="paxname", type="string", length=255)
     */
    private $paxname;

    /**
     * @var string
     *
     * @ORM\Column(name="paxlastname", type="string", length=255)
     */
    private $paxlastname;

    /**
     * @var string
     *
     * @ORM\Column(name="paxemail", type="string", length=255)
     */
    private $paxemail;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="birthdate", type="date")
     */
    private $birthdate;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="ipclient", type="string", length=255)
     */
    private $ipclient;

    /**
     * @var \Daiquiri\AdminBundle\Entity\Gender
     *
     * @ORM\ManyToOne(targetEntity="Daiquiri\ReservationBundle\Entity\Gender", inversedBy="service_paxs")
     * @ORM\JoinColumns({
     *   @ORM\JoinColumn(name="gender", referencedColumnName="id")
     * })
     */
    private $gender;

    /**
     * @var string
     *
     * @ORM\Column(name="captcha", type="string", length=255)
     */
    private $captcha;

    /**
     * @var string
     *
     * @ORM\Column(name="sendclientrequest", type="boolean", options={"dafault"=false})
     */
    private $sendclientrequest;

    /**
     * @var string
     *
     * @ORM\Column(name="sendagentrequest", type="boolean", options={"dafault"=false})
     */
    private $sendagentrequest;

    /**
     * @var string
     * @ORM\Column(name="remarks", type="string", length=2000, nullable=true)
     */
    private $remarks;

    /**
     * Get id
     *
     * @return integer
     */
    public function getId() {
        return $this->id;
    }

    /**
     * Set createAt
     *
     * @param \DateTime $createAt
     *
     * @return Request
     */
    public function setCreateAt($createAt) {
        $this->createAt = $createAt;

        return $this;
    }

    /**
     * Get createAt
     *
     * @return \DateTime
     */
    public function getCreateAt() {
        return $this->createAt;
    }

    /**
     * Set paxname
     *
     * @param string $paxname
     *
     * @return Request
     */
    public function setPaxname($paxname) {
        $this->paxname = $paxname;

        return $this;
    }

    /**
     * Get paxname
     *
     * @return string
     */
    public function getPaxname() {
        return $this->paxname;
    }

    /**
     * Set paxlastname
     *
     * @param string $paxlastname
     *
     * @return Request
     */
    public function setPaxlastname($paxlastname) {
        $this->paxlastname = $paxlastname;

        return $this;
    }

    /**
     * Get paxlastname
     *
     * @return string
     */
    public function getPaxlastname() {
        return $this->paxlastname;
    }

    /**
     * Set birthdate
     *
     * @param \DateTime $birthdate
     *
     * @return Request
     */
    public function setBirthdate($birthdate) {
        $this->birthdate = $birthdate;

        return $this;
    }

    /**
     * Get birthdate
     *
     * @return \DateTime
     */
    public function getBirthdate() {
        return $this->birthdate;
    }

    /**
     * Set captcha
     *
     * @param string $captcha
     *
     * @return Request
     */
    public function setCaptcha($captcha) {
        $this->captcha = $captcha;

        return $this;
    }

    /**
     * Get captcha
     *
     * @return string
     */
    public function getCaptcha() {
        return $this->captcha;
    }

    /**
     * Set paxemail
     *
     * @param string $paxemail
     *
     * @return Request
     */
    public function setPaxemail($paxemail) {
        $this->paxemail = $paxemail;

        return $this;
    }

    /**
     * Get paxemail
     *
     * @return string
     */
    public function getPaxemail() {
        return $this->paxemail;
    }

    /**
     * Set gender
     *
     * @param \Daiquiri\ReservationBundle\Entity\Gender $gender
     *
     * @return Request
     */
    public function setGender(\Daiquiri\ReservationBundle\Entity\Gender $gender = null) {
        $this->gender = $gender;

        return $this;
    }

    /**
     * Get gender
     *
     * @return \Daiquiri\ReservationBundle\Entity\Gender
     */
    public function getGender() {
        return $this->gender;
    }

    public function getCartitem() {
        $cart = new RentalHouseRoomItem();
        return $cart;
    }

    public function getFullClientName() {
        return $this->paxname . ' ' . $this->paxlastname;
    }

    /**
     * Set ipclient
     *
     * @param string $ipclient
     *
     * @return Request
     */
    public function setIpclient($ipclient) {
        $this->ipclient = $ipclient;

        return $this;
    }

    /**
     * Get ipclient
     *
     * @return string
     */
    public function getIpclient() {
        return $this->ipclient;
    }

    public function getPaxage() {
        return $this->birthdate->diff(new \DateTime('today'))->y;
    }

    public static function getRootViewFolder() {
        return 'Default';
    }

    /**
     * Set remarks
     *
     * @param string $remarks
     *
     * @return Request
     */
    public function setRemarks($remarks) {
        $this->remarks = $remarks;

        return $this;
    }

    /**
     * Get remarks
     *
     * @return string
     */
    public function getRemarks() {
        return $this->remarks;
    }

    public function getFullInfo() {
        
    }

    /**
     * Set sendclientrequest
     *
     * @param boolean $sendclientrequest
     *
     * @return Request
     */
    public function setSendclientrequest($sendclientrequest) {
        $this->sendclientrequest = $sendclientrequest;

        return $this;
    }

    /**
     * Get sendclientrequest
     *
     * @return boolean
     */
    public function getSendclientrequest() {
        return $this->sendclientrequest;
    }

    /**
     * Set sendagentrequest
     *
     * @param boolean $sendagentrequest
     *
     * @return Request
     */
    public function setSendagentrequest($sendagentrequest) {
        $this->sendagentrequest = $sendagentrequest;

        return $this;
    }

    /**
     * Get sendagentrequest
     *
     * @return boolean
     */
    public function getSendagentrequest() {
        return $this->sendagentrequest;
    }

}

src/Daiquiri/ReservationBundle/Entity/ServicePax.php
<?php

namespace Daiquiri\ReservationBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * ServicePax
 *
 * @ORM\Table()
 * @ORM\Entity
 */
class ServicePax {

    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="name", type="string", length=255)
     */
    private $name;

    /**
     * @var DateTime
     *
     * @ORM\Column(name="birthdate", type="date", length=255)
     */
    private $birthdate;

    /**
     * @var string
     *
     * @ORM\Column(name="lastname", type="string", length=255)
     */
    private $lastname;

    /**
     * @var string
     *
     * @ORM\Column(name="document", type="string", length=255)
     */
    private $document;

    /**
     * @var \Daiquiri\AdminBundle\Entity\Gender
     *
     * @ORM\ManyToOne(targetEntity="Daiquiri\ReservationBundle\Entity\Gender", inversedBy="service_paxs")
     * @ORM\JoinColumns({
     *   @ORM\JoinColumn(name="gender", referencedColumnName="id")
     * })
     */
    private $gender;

    /**
     * @var \Daiquiri\ReservationBundle\Entity\Service
     *
     * @ORM\ManyToOne(targetEntity="Daiquiri\ReservationBundle\Entity\Service", inversedBy="servicepaxs", cascade={"all"})
     * @ORM\JoinColumns({
     *   @ORM\JoinColumn(name="service", referencedColumnName="id")
     * })
     */
    private $service;

    /**
     * Get id
     *
     * @return integer
     */
    public function getId() {
        return $this->id;
    }

    /**
     * Set name
     *
     * @param string $name
     *
     * @return ServicePax
     */
    public function setName($name) {
        $this->name = $name;

        return $this;
    }

    /**
     * Get name
     *
     * @return string
     */
    public function getName() {
        return $this->name;
    }

    /**
     * Set lastname
     *
     * @param string $lastname
     *
     * @return ServicePax
     */
    public function setLastname($lastname) {
        $this->lastname = $lastname;

        return $this;
    }

    /**
     * Get lastname
     *
     * @return string
     */
    public function getLastname() {
        return $this->lastname;
    }

    /**
     * Set document
     *
     * @param string $document
     *
     * @return ServicePax
     */
    public function setDocument($document) {
        $this->document = $document;

        return $this;
    }

    /**
     * Get document
     *
     * @return string
     */
    public function getDocument() {
        return $this->document;
    }

    /**
     * Set gender
     *
     * @param \Daiquiri\ReservationBundle\Entity\Gender $gender
     *
     * @return ServicePax
     */
    public function setGender(\Daiquiri\ReservationBundle\Entity\Gender $gender = null) {
        $this->gender = $gender;

        return $this;
    }

    /**
     * Get gender
     *
     * @return \Daiquiri\ReservationBundle\Entity\Gender
     */
    public function getGender() {
        return $this->gender;
    }

    /**
     * Set service
     *
     * @param \Daiquiri\ReservationBundle\Entity\Service $service
     *
     * @return ServicePax
     */
    public function setService(\Daiquiri\ReservationBundle\Entity\Service $service = null) {
        $this->service = $service;

        return $this;
    }

    /**
     * Get service
     *
     * @return \Daiquiri\ReservationBundle\Entity\Service
     */
    public function getService() {
        return $this->service;
    }

    public function __toString() {
        return strtoupper($this->getGender() . " " . $this->name . " " . $this->lastname);
    }

    /**
     * Set birthdate
     *
     * @param \DateTime $birthdate
     *
     * @return ServicePax
     */
    public function setBirthdate($birthdate) {
        $this->birthdate = $birthdate;

        return $this;
    }

    /**
     * Get birthdate
     *
     * @return \DateTime
     */
    public function getBirthdate() {
        return $this->birthdate;
    }
    
    public function __construct() {
        $this->birthdate =  (new \DateTime('now'))->modify('-18 years');
    }
    
    public function getAge() {
        return $this->birthdate->diff(new \DateTime('today'))->y;
    }
}

src/Daiquiri/ReservationBundle/Resources/views/Excursion/form_searcher_into_excursion.html.twig
{# empty Twig template #}
{% extends "DaiquiriReservationBundle:Default:find_form.html.twig"%}
{% block form_searcher %}            

    <div class="col-md-12">
        <div class="row">      
            <div class="col-md-12">
                <div class="box box-primary">

                    <div class="box-header">
                        <h4 class="box-title">

                            {% if searcher.excursion is defined and form is defined %} 
                                Search Availability For {{ searcher.excursion.getTipo() }} <b>{{ searcher.excursion | upper }} </b>

                            {% else %} 
                                Excursion  not found
                            {% endif %}
                        </h4>
                    </div>
                    {% if searcher is defined and form is defined %}
                        <div class="box-body">
                            <div class="sonata-ba-collapsed-fields">



                                {{ form_start(form, {'action': admin.generateUrl('create', {'id': admin.id(searcher), 'uniqid': admin.uniqid, 'subclass': app.request.get('subclass'), 'view_render':'DaiquiriReservationBundle:Excursion:form_searcher_into_excursion.html.twig'}), 'method': 'POST'}) }}
                                {{ form_errors(form) }}
                                <div class="hidden">
                                    {{ form_widget(form.types) }} 
                                    {{ form_widget(form.exclusive,{'value':searcher.exclusive }) }} 
                                    {{ form_widget(form.polo) }} 
                                    {{ form_widget(form.places) }} 
                                    {{ form_widget(form.polofrom) }} 
                                    {{ form_widget(form.duration) }} 
                                    {{ form_widget(form.excursion,{'value':searcher.excursion.id}) }} 
                                </div>

                                <div class="row">
                                    <div class="col-md-3">
                                        <div>
                                            {{ form_label(form.date) }}
                                            <div class="sonata-ba-field sonata-ba-field-standard-natural">
                                                {{ form_widget(form.date) }} 
                                            </div>
                                        </div>
                                    </div>

                                    <div class="col-md-2">
                                        <div>
                                            {{ form_label(form.adults) }}
                                            <div class="sonata-ba-field sonata-ba-field-standard-natural">
                                                {{ form_widget(form.adults) }} 
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-md-2">
                                        <div>
                                            {{ form_label(form.kids) }}
                                            <div class="sonata-ba-field sonata-ba-field-standard-natural">
                                                {{ form_widget(form.kids) }} 
                                            </div>
                                        </div>
                                    </div>



                                    <div class="col-md-1">
                                        <div>
                                            &nbsp;
                                            <div class="sonata-ba-field sonata-ba-field-standard-natural">
                                                <button name="btn_create_and_edit" type="submit" class="btn btn-info"><i class="fa fa-save"></i> Search</button> 
                                            </div>
                                        </div>
                                    </div>
                                    {{ form_end(form) }}
                                </div>

                                <div class="margin">
                                    <span class="label label-warning">Info</span>
                                    This excursion is available for 
                                    {% if searcher.excursion.monday %}
                                        <b> Monday &nbsp; </b> | 
                                    {% endif %}
                                    {% if searcher.excursion.thuesday %}
                                        <b> Thuesday &nbsp; </b> |
                                    {% endif %}
                                    {% if searcher.excursion.wednesday %}
                                        <b> Wednesday &nbsp; </b> |
                                    {% endif %}
                                    {% if searcher.excursion.thursday %}
                                        <b>  Thursday &nbsp;  </b>|
                                    {% endif %}
                                    {% if searcher.excursion.friday %}
                                        <b> Friday &nbsp; </b>|
                                    {% endif %}
                                    {% if searcher.excursion.saturday %}
                                        <b> Saturday &nbsp; </b> |
                                    {% endif %}                                       
                                    {% if searcher.excursion.sunday %}
                                        <b> Sunday &nbsp;  </b>|
                                    {% endif %}

                                    {% if not searcher.exclusive %}
                                        <span class="label label-warning">Info</span> The excursion required {{ searcher.excursion.minpax }} Min pax.
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                    {% else %} Excursion not found{% endif %}
                </div>

            </div>
        </div>
    </div>
    {% if salida is defined and salida | length >0%}
        {% for s in salida %}           
            <div class="col-md-12">
                <div class="row">   
                    <div class="col-md-12">


                        <div class="box box-primary">
                            <div class="box-header">
                                <h4 class="box-title">
                                    {% if s.colective %}
                                        <span class="label label-primary">Shared Excursion</span>
                                    {% else %}
                                        <span class="label label-info">Exclusive Excursion</span>
                                    {% endif %}
                                    {{ s.obj }}
                                </h4>
                            </div>
                            <div class="box-body">   
                                {% if s.colective %}
                                    {% set admin = 'admin.excursioncolective' %}
                                {% else %}
                                    {% set admin = 'admin.excursionexclusive' %}
                                {% endif %}
                                {% render(controller('DaiquiriReservationBundle:ExcursionSearcher:renderResultItem',{ '_sonata_admin' : admin,'item':s})) %}                               
                            </div>
                        </div>


                    </div>
                </div>
            </div>
            <div class="row"></div>
        {% endfor %}
    {% endif %}

{% endblock %}

src/Daiquiri/ReservationBundle/Resources/views/Excursion/full_search_result.html.twig
{# empty Twig template #}
{% extends base_template %}

{#{% block tab_menu %}{{ knp_menu_render(admin.sidemenu(action), {'currentClass' : 'active', 'template': admin_pool.getTemplate('tab_menu_template')}, 'twig') }}{% endblock %}#}

{% block show %}
    {% include 'SonataCoreBundle:FlashMessage:render.html.twig' %}
    <div class="box box-primary">
        <div class="box-header with-border">
            <h3 class="box-title">    <i class="fa fa-refresh"></i> Excursion</h3>
        </div>
        <!-- /.box-header -->
        <!-- form start -->

        <div class="box-body">
            {% render(controller('DaiquiriReservationBundle:ExcursionSearcher:getFullExcursionSearcher',{ '_sonata_admin' : 'admin.excursion.searcher','data':searcher}))%}   
        </div>   </div>
            {% if salida is defined and salida | length >0 %}
        {% for s in salida %}
            <div class="col-md-12">
                <div class="row">
                    <div class="box box-primary">
                        <div class="box-header">
                            <h4 class="box-title">
                                {% if s.colective %}
                                    <span class="label label-primary">Shared Excursion</span>
                                {% else %}
                                    <span class="label label-info">Exclusive Excursion</span>
                                {% endif %}
                                {{ s.obj }}
                            </h4>
                        </div>
                        <div class="box-body">   
                            {% if s.colective %}
                                {% set admin = 'admin.excursioncolective' %}
                            {% else %}
                                {% set admin = 'admin.excursionexclusive' %}
                            {% endif %}
                            {% render(controller('DaiquiriReservationBundle:ExcursionSearcher:renderResultItem',{ '_sonata_admin' : admin,'item':s})) %}                               
                        </div>
                    </div>

                </div>
            </div>
            <div class="row"></div>
        {% endfor %}
    {% endif %}

{% endblock %}

src/Daiquiri/ReservationBundle/Resources/views/Excursion/full_searcher.html.twig
<div class="sonata-ba-collapsed-fields">
    {{ form_start(form, {'action': admin.generateUrl('create', {'id': admin.id(object), 'uniqid': admin.uniqid, 'subclass': app.request.get('subclass')}), 'method': 'POST'}) }}
    {{ form_errors(form) }}
    <div class="row">
        <div class="col-md-2">
            <div>
                {{ form_label(form.date) }}
                <div class="sonata-ba-field sonata-ba-field-standard-natural">
                    {{ form_widget(form.date, {'id':'date'}) }} 
                </div>
            </div>
        </div>

        <div class="col-md-2">
            <div>
                {{ form_label(form.exclusive) }}
                <div class="sonata-ba-field sonata-ba-field-standard-natural">
                    {{ form_widget(form.exclusive) }} 
                </div>
            </div>
        </div>


        <div class="col-md-2">
            <div>
                {{ form_label(form.polo) }}
                <div class="sonata-ba-field sonata-ba-field-standard-natural">
                    {{ form_widget(form.polo) }} 
                </div>
            </div>
        </div>
        <div class="col-md-1">
            <div>
                {{ form_label(form.adults) }}
                <div class="sonata-ba-field sonata-ba-field-standard-natural">
                    {{ form_widget(form.adults) }} 
                </div>
            </div>
        </div>
        <div class="col-md-1">
            <div>
                {{ form_label(form.kids) }}
                <div class="sonata-ba-field sonata-ba-field-standard-natural">
                    {{ form_widget(form.kids) }} 
                </div>
            </div>
        </div>
        <div class="col-md-2">
            <div>
                {{ form_label(form.types) }}
                <div class="sonata-ba-field sonata-ba-field-standard-natural">
                    {{ form_widget(form.types) }} 
                </div>
            </div>
        </div>




        <div class="col-md-12"><a href="#advance_excursion" class="advance_excursion">Advance Option</a></div>
        <div class="advance_hotel hidden">      
            <div class="col-md-2">
                <div>
                    {{ form_label(form.polofrom) }}
                    <div class="sonata-ba-field sonata-ba-field-standard-natural">
                        {{ form_widget(form.polofrom) }} 
                    </div>
                </div>
            </div>
            <div class="col-md-2">
                <div>
                    {{ form_label(form.places) }}
                    <div class="sonata-ba-field sonata-ba-field-standard-natural">
                        {{ form_widget(form.places) }} 
                    </div>
                </div>
            </div>
            <div class="col-md-2">
                <div>
                    {{ form_label(form.duration) }}
                    <div class="sonata-ba-field sonata-ba-field-standard-natural">
                        {{ form_widget(form.duration) }} 
                    </div>
                </div>
            </div>
            <div class="col-md-2">
                <div>
                    {{ form_label(form.excursion) }}
                    <div class="sonata-ba-field sonata-ba-field-standard-natural">
                        {{ form_widget(form.excursion) }} 
                    </div>
                </div>
            </div>


        </div>

        <div class="pull-right margin-right-10">
            <div>
                &nbsp;
                <div class="sonata-ba-field sonata-ba-field-standard-natural">
                    <button name="btn_create_and_edit" type="submit" class="btn btn-info"><i class="fa fa-search"></i> Search</button> 
                </div>
            </div>
        </div>
        {{ form_end(form) }}
        <script>

            $('.advance_excursion').each(function () {

                $(this).click(function (e) {
                    e.preventDefault();
                    // console.log('lolo' + $(this).parent().next());
                    $(this).parent().next().toggleClass('hidden');
                });
            });

        </script>
    </div>
</div>

src/Daiquiri/ReservationBundle/Resources/views/Excursion/item_cart_min.html.twig
<li id="{{ it.id }}" class="item_cart">
    <a href="#" class="cart">

        <div class="pull-left"> 
            <i class="fa fa-tree fa-2x img-circle thumbnail_cart"> </i>

        </div> 
        <div class="margin-left-40">
            <div>
                <h4><span class="text-blue">{{ it.product.type }}</span><small class="pull-right text-success">{{ it.getTotalprice() | price | raw }}</small></h4>
            </div>
            <div>
                <small><i class="fa fa-tree"></i> {{ product.getTitle() }} x {{ it.quantity }}</small>
            </div>
            <div>
                <small><i class="fa fa-calendar"></i> {{ it.startdate | date('M j, Y') }}</small> 
                <small><i class="fa fa-map-marker"></i> {{ it.pickupplace }}</small> 
            </div>
            <div>
                <small><i class="fa fa-user fa-lg"></i> Adult(s) :{{ it.adult }}</small> 
                <small><i class="fa fa-user"></i> Kid(s) : {{ it.kid }}</small>
            </div>
        </div>
    </a>
</li>

src/Daiquiri/ReservationBundle/Resources/views/Excursion/pdf_voucher.html.twig
{# empty Twig template #}
{% extends '::pdf_voucher.html.twig' %}

{% block tabla %}
    {% set colective = service.cartitem.product.getColective() %}
    <tr>
        <td colspan="2" align="left" style="border-bottom: solid 1px #ccc">

            <div style="font-size: 13px;">
                {% if colective %} {{ 'Shared Excursion Voucher' | trans({}, 'pdf') }}{% else %} {{ 'Private' | trans({}, 'pdf') }}{% endif %}
                {{ 'Private Excursion Voucher' | trans({}, 'pdf') }}</div>
        </td>
        <td colspan="2" align="right" style="border-bottom: solid 1px #ccc">
            <div style=""><span style="font-size: 8px; font-style: italic">{{ 'Client' | trans({}, 'pdf') }}: </span>{{ service.sale.client.getFullName() | upper }}</div>
        </td>
    </tr>
    <tr>
        <td style="border-right: solid 1px #ccc">
            <div>  <span style="font-size: 8px; font-style: italic">{{ 'Excursion' | trans({}, 'pdf') }}: </span>{{ service.cartitem.product.title  }}</div>

        </td>
        <td style="border-right: solid 1px #ccc">
            <div>  <span style="font-size: 8px; font-style: italic">{{ 'Adult' | trans({}, 'pdf') }}: </span>{{ service.cartitem.adult  }}
                <span style="font-size: 8px; font-style: italic">{{ 'Kid' | trans({}, 'pdf') }}: </span>{{ service.cartitem.kid  }}</div>

        </td>

        <td style="border-right: solid 1px #ccc">
            <div>  <span style="font-size: 8px; font-style: italic">{{ 'Departure' | trans({}, 'pdf') }}: </span>{{ service.cartitem.startdate | date('M j, Y') }}</div>

        </td>

        <td style="border-right: solid 1px #ccc">
            <div>
                <span style="font-size: 8px; font-style: italic">{{ 'Pickupplace' | trans({}, 'pdf') }}: </span>{{ service.cartitem.pickupplace.fullTitle  }}
                 <span style="font-size: 8px; font-style: italic">{{ 'Province' | trans({}, 'pdf') }}: </span>{{ service.cartitem.pickupplace.province  }}
            </div>

        </td>


    </tr>
    <tr>
        <td colspan="4"></td>
    </tr>


{% endblock %}
{% block pax %}
    <tr>
        {% if service.confirmationcode is not null %}
            <td colspan="2" align="left" style="border-bottom: solid 1px #ccc">
                <div style="font-size: 10px; "> {{ 'Pax(s)' | trans({}, 'pdf') }} </div>
            </td>
            <td colspan="2" align="right" style="border-bottom: solid 1px #ccc">
                <div style="font-size: 10px; "><span style="font-size: 8px; font-style: italic">{{ 'Corfirmation Code' | trans({}, 'pdf') }} :</span> {{ service.confirmationcode | upper}} </div>
            </td>
        {% else %}

            <td colspan="4" align="left" style="border-bottom: solid 1px #ccc">
                <div style="font-size: 10px; "> {{ 'Pax(s)' | trans({}, 'pdf') }} </div>
            </td>
        {% endif %}

    </tr>

    {% for pax in service.servicepaxs %}
        <tr>
            {% if service.cartitem.arraypaxs[loop.index - 1] == 1 %}
                <td style="border-right: solid 1px #ccc"><span style="font-size: 8px; font-style: italic">{{ 'Adult' | trans({}, 'pdf') }} {{ loop.index }} </span></td> 
            {% endif%}
            {% if service.cartitem.arraypaxs[loop.index - 1] == 2 %}
                <td style="border-right: solid 1px #ccc"><span style="font-size: 8px; font-style: italic">{{ 'Kid' | trans({}, 'pdf') }} {{ loop.index }} </span></td>
            {% endif%}
            {% if service.cartitem.arraypaxs[loop.index - 1] == 3 %}
                <td style="border-right: solid 1px #ccc"><span style="font-size: 8px; font-style: italic">{{ 'Infant' | trans({}, 'pdf') }} {{ loop.index }} </span></td> 
            {% endif%}
            {% if service.cartitem.arraypaxs[loop.index - 1] == 4 %}
                <td style="border-right: solid 1px #ccc"><span style="font-size: 8px; font-style: italic">{{ 'Passenger' | trans({}, 'pdf') }} {{ loop.index }} </span></td> 
            {% endif%}

            <td style="border-right: solid 1px #ccc"><span style="font-size: 8px; font-style: italic">{{ pax.gender }}. {{ pax.name | upper }} {{ pax.lastname | upper }}</span></td>
            <td style="border-right: solid 1px #ccc"><span style="font-size: 8px; font-style: italic">ID: {{ pax.document | upper }}   </span></td>
            <td style="border-right: solid 1px #ccc"><span style="font-size: 8px; font-style: italic">{{ pax.age }} {{ 'Years' | trans({}, 'pdf') }}  </span></td>
        </tr>
    {% endfor %}

{% endblock %}